version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/aegis-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/aegis-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
